# Generated by Django 5.2.6 on 2025-09-19 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('departament', models.CharField(choices=[('LIBRARY', 'Biblioteca'), ('ADMINISTRATIVE_BUILDING', 'Secretaria'), ('TEACHERS_ROOM', 'Sala dos Professores'), ('CLASSROOM', 'Sala de Aula'), ('LABORATORY', 'Laboratório'), ('COMPUTER_LAB', 'Laboratório de Informática'), ('CAFETERIA', 'Refeitório'), ('AUDITORIUM', 'Auditório'), ('MUSIC_ROOM', 'Sala de Música'), ('ART_ROOM', 'Sala de Artes'), ('STORAGE_ROOM', 'Depósito'), ('PRINCIPAL_OFFICE', 'Diretoria'), ('NURSE_OFFICE', 'Enfermaria'), ('RECEPTION', 'Recepção'), ('STAFF_ROOM', 'Sala de Funcionários')], max_length=100)),
                ('tag_number', models.IntegerField(blank=True, unique=True)),
                ('serial_number', models.CharField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField()),
                ('departament', models.CharField(choices=[('LIBRARY', 'Biblioteca'), ('ADMINISTRATIVE_BUILDING', 'Secretaria'), ('TEACHERS_ROOM', 'Sala dos Professores'), ('CLASSROOM', 'Sala de Aula'), ('LABORATORY', 'Laboratório'), ('COMPUTER_LAB', 'Laboratório de Informática'), ('CAFETERIA', 'Refeitório'), ('AUDITORIUM', 'Auditório'), ('MUSIC_ROOM', 'Sala de Música'), ('ART_ROOM', 'Sala de Artes'), ('STORAGE_ROOM', 'Depósito'), ('PRINCIPAL_OFFICE', 'Diretoria'), ('NURSE_OFFICE', 'Enfermaria'), ('RECEPTION', 'Recepção'), ('STAFF_ROOM', 'Sala de Funcionários')], max_length=100)),
                ('creation_date', models.DateField(auto_now=True)),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('asset_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Request_asset_FK', to='app.asset')),
                ('user_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Request_user_FK', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='fotos/')),
                ('request_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Photo_request_FK', to='app.request')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('OPEN', 'Em Aberto'), ('IN_PROGRESS', 'Em andamento'), ('CLOSED', 'Fechado')], max_length=100)),
                ('date_of_modification', models.DateField(auto_now=True)),
                ('changed_by_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Status_changed_by_FK', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='status_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Request_user_FK', to='app.status'),
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_change', models.DateTimeField(auto_now_add=True)),
                ('changed_by_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_history_user', to=settings.AUTH_USER_MODEL)),
                ('request_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='app.request')),
                ('status_FK', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_history_status', to='app.status')),
            ],
        ),
    ]
