# Generated by Django 5.2.6 on 2025-09-18 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('departament', models.CharField(choices=[('LIBRARY', 'Biblioteca'), ('ADMINISTRATIVE_BUILDING', 'Secretaria'), ('TEACHERS_ROOM', 'Sala dos Professores'), ('CLASSROOM', 'Sala de Aula'), ('LABORATORY', 'Laboratório'), ('COMPUTER_LAB', 'Laboratório de Informática'), ('CAFETERIA', 'Refeitório'), ('AUDITORIUM', 'Auditório'), ('MUSIC_ROOM', 'Sala de Música'), ('ART_ROOM', 'Sala de Artes'), ('STORAGE_ROOM', 'Depósito'), ('PRINCIPAL_OFFICE', 'Diretoria'), ('NURSE_OFFICE', 'Enfermaria'), ('RECEPTION', 'Recepção'), ('STAFF_ROOM', 'Sala de Funcionários')], max_length=100)),
                ('tag_number', models.IntegerField()),
                ('serial_number', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('OPEN', 'Em Aberto'), ('IN_PROGRESS', 'Em andamento'), ('CLOSED', 'Fechado')], max_length=100)),
                ('date_of_modification', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField()),
                ('creation_date', models.DateField()),
                ('closing_date', models.DateField()),
                ('asset_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Request_asset_FK', to='app.asset')),
                ('status_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Request_user_FK', to='app.status')),
                ('user_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Request_user_FK', to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='fotos/')),
                ('request_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Photo_request_FK', to='app.request')),
            ],
        ),
        migrations.AddField(
            model_name='status',
            name='changed_by_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Status_changed_by_FK', to='app.user'),
        ),
    ]
