# Generated by Django 5.2.6 on 2025-09-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='closing_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='creation_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
