# Generated by Django 5.2.6 on 2025-10-03 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='urgency_level',
            field=models.CharField(choices=[('LOW', 'low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('EXTRA_HIGH', 'Extra High')], default='LOW', max_length=50),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(choices=[('OPEN', 'Open'), ('WAITING_ASSIGNEE', 'Waiting Assignee'), ('ONGOING', 'Ongoing'), ('DONE', 'Done'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], max_length=100),
        ),
    ]
