# Generated by Django 5.2.6 on 2025-12-06 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestimage',
            name='uploaded_at',
        ),
    ]
