# Generated by Django 5.2.7 on 2025-10-08 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_request_urgency_level_alter_status_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='serial_number',
        ),
    ]
