# Generated by Django 5.2.6 on 2025-09-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_request_closing_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='message_of_closing',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='description',
            field=models.TextField(),
        ),
    ]
