# Generated by Django 5.2.6 on 2025-12-06 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_requestimage_uploaded_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
