# Generated by Django 5.2.7 on 2025-10-08 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_asset_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='urgency_level',
            field=models.CharField(choices=[('LOW', 'Baixa'), ('Médio', 'Medium'), ('Alta', 'High'), ('Extremamente alta', 'Extra High')], default='LOW', max_length=50),
        ),
    ]
