# Generated by Django 5.2.6 on 2025-09-23 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_request_message_of_closing_alter_request_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='message_of_closing',
            new_name='closing_message',
        ),
    ]
