# Generated by Django 5.2.7 on 2025-10-08 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_request_urgency_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='urgency_level',
            field=models.CharField(choices=[('LOW', 'Baixa'), ('MEDIUM', 'Médio'), ('HIGH', 'Alta'), ('EXTRA_HIGH', 'Extremamente alta')], default='LOW', max_length=50),
        ),
    ]
