# Generated by Django 5.2.6 on 2025-12-03 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_request_urgency_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(choices=[('OPEN', 'Aberto'), ('WAITING_ASSIGNEE', 'Aguardando Atribuição'), ('ONGOING', 'Em Andamento'), ('DONE', 'Concluído'), ('CLOSED', 'Fechado'), ('CANCELLED', 'Cancelado')], max_length=100),
        ),
        migrations.CreateModel(
            name='RequestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='request_images')),
                ('task_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RequestStatusImage_request_FK', to='app.request')),
            ],
        ),
    ]
